# 爬虫配置
crawler:
  base_url: "https://www.aibase.com/zh/news/"
  max_articles: 10
  timeout: 30
  user_agent: "Mozilla/5.0"

# 智谱AI配置
zhipuai:
  api_key: "your_api_key"
  base_url: "https://open.bigmodel.cn/api/paas/v4"
  model: "glm-4-flash"
  temperature: 0.7
  max_tokens: 1000

# 早报生成配置
generator:
  title: "AI早报"
  max_summaries: 5
  output_dir: "output"
  output_file: "daily_report.md"

# 发送配置
sender:
  enabled: true
  # 支持同时使用多个发送方式
  types: ["smtp", "wechat_work"]
  
  # 企业微信机器人配置
  wechat_work:
    enabled: true
    webhook_url: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=your_key"
    max_attachments: 10  # 最大附件数量
    attachment_types: [".md"]  # 允许的附件类型
  
  # SMTP邮件配置
  smtp:
    enabled: true
    host: "smtp.example.com"
    port: 465
    user: "your_email@example.com"
    password: "your_email_password"
    from: "your_email@example.com"
    to: "recipient@example.com"
    max_attachments: 10  # 最大附件数量
    attachment_types: [".md", ".txt"]  # 允许的附件类型

# 日志配置
logging:
  level: INFO
  max_bytes: 10485760
  backup_count: 5
